version: "3.9"

services:
  db:
    image: postgres:16
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # host:container (5433 en host para no chocar con PG local)
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: roger/restaurant-api:1.0   # solo usa la imagen ya creada
    container_name: restaurant-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL_DEV: jdbc:postgresql://db:5432/restaurant
      DB_USER_DEV: postgres
      DB_PASSWORD_DEV: postgres
      STORAGE_URL: https://dummy.supabase.co
      SUPABASE_SERVICE_ROLE: dummy_service_role_key
      STORAGE_BUCKET: dummy-bucket
    ports:
      - "8080:8080"

volumes:
  pgdata:
