name: Spring Boot CI # Nombre del workflow que aparecerá en la lista de acciones

on:
  push:
    branches: [ master , rama1 ] # Ejecutar el workflow al hacer push en la rama master, para incluir otras ramas [ master, rama1 ]
  pull_request:
    branches: [ master , rama1 ] # También ejecutar cuando se abre un pull request hacia master, para incluir otras ramas [ master, rama1 ]

jobs:
  build:
    runs-on: ubuntu-latest # Usar la última versión estable de Ubuntu como runner

    steps:
      - name: Checkout del código fuente # Clonar el repositorio en el runner
        uses: actions/checkout@v4

      - name: Configurar Java 17 # Instalar y configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir y ejecutar tests con Maven (modo debug) # Compilar y testear el proyecto con Maven
        run: mvn -X clean verify